Debug, Errors

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,46 +27,48 @@ workflows:
                   
                   is_prod_release=`git diff --name-only origin/main...$CIRCLE_SHA1 prod/*.yml | wc -l`
                   is_preprod_release=`git diff --name-only origin/main...$CIRCLE_SHA1 preprod/*.yml | wc -l`
-                    if [ ${is_prod_release} = 1 ];
-                      then
-                        echo "INFO: This is a Release...."
-                        is_release=true
 
-                        # Evaluate Java Image Tag, this is required to handle different Java Versions for builds
-                        is_reporting_job=`git diff --name-only origin/main...$CIRCLE_SHA1 prod/digital-prison-reporting-jobs.yml | wc -l`
-                          if [ ${is_reporting_job} = 1 ];
-                          then
-                            JAVA_TAG="8.0"
-                            # Pass TAG into Params File
-                            echo ', "tag": "'"$JAVA_TAG"'" }' >> /home/circleci/params.json
-                            echo "INFO: Triggering Build using Java Image Tag: $JAVA_TAG"
-                          else
-                            echo "INFO: JAVA_TAG is set to 'default'"
-                            echo '}' >> /home/circleci/params.json
-                          fi
-                    elif [ ${is_preprod_release} = 1 ];
-                      then
-                        echo "INFO: This is a Pre-Prod Deployment...."                      
-                        is_release=false
+                  echo "INFO: IS_PROD_RELEASE: $is_prod_release, IS_PREPROD_RELEASE: $is_preprod_release"
+                  if [ ${is_prod_release} = 1 ];
+                    then
+                      echo "INFO: This is a Release...."
+                      is_release=true
 
-                        # Evaluate Java Image Tag, this is required to handle different Java Versions for builds
-                        is_reporting_job=`git diff --name-only origin/main...$CIRCLE_SHA1 preprod/digital-prison-reporting-jobs.yml | wc -l`
-                          if [ ${is_reporting_job} = 1 ];
-                          then
-                            JAVA_TAG="8.0"
-                            # Pass TAG into Params File
-                            echo ', "tag": "'"$JAVA_TAG"'" }' >> /home/circleci/params.json
-                            echo "INFO: Triggering Build using Java Image Tag: $JAVA_TAG"
-                          else
-                            echo "INFO: JAVA_TAG is set to 'default'"
-                            echo '}' >> /home/circleci/params.json
-                          fi
-                    elif [ ${is_preprod_release} = 1 ] && [ ${is_prod_release} = 1 ];
-                      then
-                        echo "Error, Cannot Perform Release and Deploy to Preprod same Time.."
-                        echo '}' >> /home/circleci/params.json
-                        exit 1
-                    fi    
+                      # Evaluate Java Image Tag, this is required to handle different Java Versions for builds
+                      is_reporting_job=`git diff --name-only origin/main...$CIRCLE_SHA1 prod/digital-prison-reporting-jobs.yml | wc -l`
+                        if [ ${is_reporting_job} = 1 ];
+                        then
+                          JAVA_TAG="8.0"
+                          # Pass TAG into Params File
+                          echo ', "tag": "'"$JAVA_TAG"'" }' >> /home/circleci/params.json
+                          echo "INFO: Triggering Build using Java Image Tag: $JAVA_TAG"
+                        else
+                          echo "INFO: JAVA_TAG is set to 'default'"
+                          echo '}' >> /home/circleci/params.json
+                        fi
+                  elif [ ${is_preprod_release} = 1 ];
+                    then
+                      echo "INFO: This is a Pre-Prod Deployment...."                      
+                      is_release=false
+
+                      # Evaluate Java Image Tag, this is required to handle different Java Versions for builds
+                      is_reporting_job=`git diff --name-only origin/main...$CIRCLE_SHA1 preprod/digital-prison-reporting-jobs.yml | wc -l`
+                        if [ ${is_reporting_job} = 1 ];
+                        then
+                          JAVA_TAG="8.0"
+                          # Pass TAG into Params File
+                          echo ', "tag": "'"$JAVA_TAG"'" }' >> /home/circleci/params.json
+                          echo "INFO: Triggering Build using Java Image Tag: $JAVA_TAG"
+                        else
+                          echo "INFO: JAVA_TAG is set to 'default'"
+                          echo '}' >> /home/circleci/params.json
+                        fi
+                  elif [ ${is_preprod_release} = 1 ] && [ ${is_prod_release} = 1 ];
+                    then
+                      echo "Error, Cannot Perform Release and Deploy to Preprod same Time.."
+                      echo '}' >> /home/circleci/params.json
+                      exit 1
+                  fi    
                     cat /home/circleci/params.json 
           requires: [clone]        
            
